coverage:
  status:
    patch:
      default:
        target: 70%
    project:                   # measuring the overall project coverage
      default:                 # context, you can create multiple ones with custom titles
        target: 80%             # specify the target coverage for each commit status