coverage:
  status:
    patch:
      default:
        target: 90%
    project:                   # measuring the overall project coverage
        default:                 # context, you can create multiple ones with custom titles
          target: 90%             # specify the target coverage for each commit status
  


